name: clawdbot
region: tor  # Toronto (default)
# Available regions: nyc, ams, sfo, sgp, lon, fra, blr, syd, tor

features:
  - buildpack-stack=ubuntu-22

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

ingress: {}

# Worker (not service) - Tailscale provides networking, no public HTTP endpoint
workers:
  - name: clawdbot
    dockerfile_path: /Dockerfile
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
      repo: digitalocean-labs/clawdbot-appplatform
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb  # 1 vCPU, 1GB RAM (~$12/mo)
    envs:
      # === Required ===
      - key: SETUP_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: TS_AUTHKEY
        scope: RUN_TIME
        type: SECRET

      # === Tailscale Configuration ===
      - key: TS_HOSTNAME
        scope: RUN_AND_BUILD_TIME
        value: clawdbot
      - key: TS_USERSPACE
        scope: RUN_AND_BUILD_TIME
        value: "true"
      - key: TS_SOCKET
        scope: RUN_AND_BUILD_TIME
        value: /tmp/tailscaled.sock
      - key: TS_ENABLE_HEALTH_CHECK
        scope: RUN_AND_BUILD_TIME
        value: "true"
      - key: TS_LOCAL_ADDR_PORT
        scope: RUN_AND_BUILD_TIME
        value: '[::]:9002'

      # === App Directories ===
      - key: CLAWDBOT_STATE_DIR
        scope: RUN_AND_BUILD_TIME
        value: /data/.clawdbot
      - key: CLAWDBOT_WORKSPACE_DIR
        scope: RUN_AND_BUILD_TIME
        value: /data/workspace

      # === Optional: AI Provider ===
      - key: GRADIENT_API_KEY
        scope: RUN_TIME
        type: SECRET

      # === Optional: Persistence via DO Spaces + Litestream ===
      # Uncomment to enable SQLite backup and state persistence
      # - key: SPACES_ENDPOINT
      #   scope: RUN_AND_BUILD_TIME
      #   value: tor1.digitaloceanspaces.com
      # - key: SPACES_BUCKET
      #   scope: RUN_AND_BUILD_TIME
      #   type: SECRET
      # - key: LITESTREAM_ACCESS_KEY_ID
      #   scope: RUN_AND_BUILD_TIME
      #   type: SECRET
      # - key: LITESTREAM_SECRET_ACCESS_KEY
      #   scope: RUN_AND_BUILD_TIME
      #   type: SECRET
